# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AdMixerSampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AdMixerSampleApp
  pod 'AdMixerMediation', '2.2.0'
  pod 'AdMixerMediationGAM', '1.0.5'
  pod 'AdMixerMediationAdFit', '1.0.6'
  pod 'AdMixerMediationPangle', '1.0.4'
  pod 'AdMixerMediationAppLovin', '1.0.3'
  pod 'AdMixerMediationUnityAds', '1.0.3'

  target 'AdMixerSampleAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AdMixerSampleAppUITests' do
    # Pods for testing
  end

end
