# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AdMixerSampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AdMixerSampleApp
  pod 'AdMixerMediation', '2.3.7'
  pod 'AdMixerMediationGAM', '1.1.0'
  pod 'AdMixerMediationAdFit', '1.1.0'
  pod 'AdMixerMediationPangle', '1.1.0'
  pod 'AdMixerMediationAppLovin', '1.0.7'
  pod 'AdMixerMediationUnityAds', '1.0.10'
  pod 'AdMixerMediationNAM', '1.1.0'

  target 'AdMixerSampleAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AdMixerSampleAppUITests' do
    # Pods for testing
  end

end
